export const // uploaderActionTypes
						 UPLOAD_TRACK = 'upload_track',
						 UPLOAD_SUCCESS = 'upload_success',
						 UPLOAD_FAILURE = 'upload_failure',
						 // trackListActiontypes
						 FETCH_TRACKS = 'fetch_tracks',
						 FETCH_TRACKS_SUCCESS = 'fetch_tracks_success',
						 FETCH_TRACKS_FAILURE = 'fetch_tracks_failure',
						 SELECT_TRACK = 'select_track',
						 TOGGLE_EDIT_MODE = 'toggle_edit_mode',
						 // playerActiontypes
						 PLAY_TRACK = 'play_track',
						 PAUSE_TRACK = 'pause_track',
						 STOP_TRACK = 'stop_track',
						 START_NEW_QUEUE = 'start_new_queue',
						 ADD_TRACK_TO_QUEUE = 'add_track_to_queue',
						 PLAY_NEXT = 'play_next',
						 PLAY_PREV = 'play_prev',
						 TOGGLE_QUEUE_VISIBILITY = 'toggle_queue_visibility',
						 POST_TRACK_DATA = 'poat_track_data',
						 POST_TRACK_DATA_SUCCESS = 'post_track_data_success',
						 POST_TRACK_DATA_FAILURE = 'post_track_data_failure',
						 DELETE_TRACK = 'delete_track',
						 DELETE_TRACK_SUCCESS = 'delete_track_success',
						 DELETE_TRACK_FAILURE = 'delete_track_failure';
