language: node_js
node_js:
  - '12'
dist: trusty
services:
  - mongodb
env:
  matrix:
    - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/mode_modules
    - server/node_modules
install:
  - npm run prodinstall
script:
  - cd client
  - yarn
  - yarn build
  - cd ../server
  - mkdir uploads
  - mkdir uploads/audio uploads/images uploads/testFiles
  - nohup npm run ci &
  - sleep 3
  - npm run ci-test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  app: jukebox
  env: Jukebox-env
  bucket_name: elasticbeanstalk-us-west-2-016190279810
  on:
    repo: phonofidelic/JukeBox
