language: node_js
node_js:
  - '12'
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run prod &
  - sleep 3
  - npm run test
